### ISSUE TITLE
actualizacion de emuladores vba-m vba-link linux-ds-pro

### ISSUE THREAD

**Issue by Eignar17** [lainz/windspro#1]
[update.zip](https://github.com/lainz/windspro/files/1023764/update.zip)

**Comment by lainz** [comment]
Hola, gracias por avisar de estos emuladores. Tengo que ver una forma de enviarlos ya compilados asi no hay que bajar tantas dependencias que al final el usuario si no es programador no va a usar. Git también sería una dependencia a tener en cuenta que no todas las distro tienen por defecto.

Estoy pensando en incluir deb's tambien, cuando tenga mas tiempo voy a seguir agregando cosas.

Podría hacerse un pack específico para Wine pero eso tendría que ser aparte, ya que no creo que todos quieran Wine. Así no mezclamos lo nativo con Windows.

**Comment by Eignar17** [comment]
entiendo este emulador facil mente se puede empaquetar no le veo problemas y gracias por la atencion!
